# Generated by Django 2.0.13 on 2019-09-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APropos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'À Propos',
                'verbose_name_plural': 'À Propos',
            },
        ),
        migrations.CreateModel(
            name='AProposSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_titre', models.CharField(max_length=200)),
                ('texte', models.TextField()),
                ('a_propos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouf.APropos')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('texte', models.TextField()),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
            },
        ),
        migrations.CreateModel(
            name='ImageAPropos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/a_propos')),
                ('legende', models.CharField(max_length=200)),
                ('a_propos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouf.APropos')),
            ],
        ),
        migrations.CreateModel(
            name='ImageEvenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/evenements')),
                ('legende', models.CharField(max_length=200)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouf.Evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='tags',
            field=models.ManyToManyField(to='ouf.Tag'),
        ),
    ]
