# Generated by Django 2.0.13 on 2019-09-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apropossection',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='imageapropos',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='imageevenement',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
