# Generated by Django 2.0.13 on 2019-09-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouf', '0002_auto_20190923_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageapropos',
            name='a_propos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ouf.APropos'),
        ),
        migrations.AlterField(
            model_name='imageevenement',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ouf.Evenement'),
        ),
    ]
