# Generated by Django 2.0.13 on 2019-09-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouf', '0003_auto_20190925_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageapropos',
            old_name='image',
            new_name='src',
        ),
        migrations.RenameField(
            model_name='imageevenement',
            old_name='image',
            new_name='src',
        ),
    ]
